### PR TITLE
Add decision letter image to kitchen sink

### PR DESCRIPTION
**Pull request by fred-atherden**

### CODE REVIEW

**Comment by fred-atherden** [comment]
FYI @gnott, we've just had one of these come through to production. Not sure if this affects the work you've been doing recently (presume that it would though!).

**Comment by gnott** [comment]
My only question until now was whether the `@id` attribute on decision letter assets need to have a different prefix, which I see you used in this sample. I think I might be able to do that, though if all the sub articles used id prefixes starting with `resp` (or something generic that works in both sub articles) it would make it easier for me.

**Comment by fred-atherden** [comment]
OK sure. I think that's one for @Melissa37 to confirm on Monday!

(I just whipped this all up quickly since it's been thrown at us in production)

CC @eLifeProduction

**Comment by Melissa37** [comment]
@FAtherden-eLife @gnott 

>@id attribute -if all the sub articles used id prefixes starting with resp (or something generic that works in both sub articles) it would make it easier for me.

That's fine by me, Fred WDYT?
something generic, like prm (aka peer review materials). Would that work?

We'd need to tell Exeter too.
M

**Comment by fred-atherden** [comment]
> That's fine by me, Fred WDYT?
> something generic, like prm (aka peer review materials). Would that work?

Fine with me!

I'll update Exeter's GitLab ticket.

**Comment by fred-atherden** [comment]
Actually on second thought - can we change it to something like `prmfig0`? That way we can use the same convention for tables `prmtable0` etc.?

**Comment by gnott** [comment]
I was able to generate different `@id` values for each sub-article in the decision letter parser library, so these names would end up as `sa2fig1` and `sa2table1` if they were in the author response. Demostration of these names in PR https://github.com/elifesciences/XML-mapping/pull/95

**Pull request merged**
