### PR TITLE
Add draft inclusion in global research form

### PR DESCRIPTION
**Pull request by fred-atherden**

### CODE REVIEW

**Comment by fred-atherden** [comment]
I've added suggested tagging for the new Inclusion in global research form. 

Feel free to add any suggestions either as comments or commits

**Review by JGilbert-eLife — APPROVED** [review]

**Comment by fred-atherden** [comment]
The form itself can be found linked to [here](https://elife-rp.msubmit.net/html/elife-rp_author_instructions.html#policies), looks like it's either a word or PDF file and the templates have the filename as `inclusion_global_research` (followed by relevant extension).

**Comment by JGilbert-eLife** [comment]
Looks good to me!

**Comment by griffithsc** [comment]
Thanks Fred - looks good to me too!

**Review by griffithsc — APPROVED** [review]

**Review by naushinthomson — APPROVED** [review]
Looks good to me!

**Pull request merged**
